spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://192.168.99.100:33306/chaos?useSSL=false
    username: chaos
    password: chaos123
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    de.codecentric: TRACE

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
                   
chaos:
  monkey:
    enabled: true
    assaults:
      level: 8
      latencyRangeStart: 1000
      latencyRangeEnd: 10000
      exceptionsActive: false
      killApplicationActive: true
    watcher:
      repository: true
      
management:
  endpoint:
    chaosmonkey:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey